import type { MenuProduct, MenuSet } from './types'

export const MENU_SETS: MenuSet[] = [
    {
        id: 'set-1',
        category: 'set',
        number: 1,
        title: 'Сет «Классика»',
        description: 'Филадельфия, Калифорния, ролл с лососем и маки с огурцом.',
        pieces: 32,
        weight: 980,
        price: 1290,
        tags: ['хит', 'лосось'],
        accent: '#f24d2c',
    },
    {
        id: 'set-2',
        category: 'set',
        number: 2,
        title: 'Сет «Филадельфия»',
        description: 'Четыре варианта филадельфии с лососем, тунцом и угрём.',
        pieces: 28,
        weight: 920,
        price: 1490,
        tags: ['сливочный сыр'],
        accent: '#ef4444',
    },
    {
        id: 'set-3',
        category: 'set',
        number: 3,
        title: 'Сет «Калифорния»',
        description: 'Калифорния с крабом, креветкой и авокадо в двух подачах.',
        pieces: 24,
        weight: 860,
        price: 1190,
        tags: ['лёгкий'],
        accent: '#10b981',
    },
    {
        id: 'set-4',
        category: 'set',
        number: 4,
        title: 'Сет «Дракон»',
        description: 'Зелёный и чёрный дракон, темпура-ролл и запечённый ролл.',
        pieces: 30,
        weight: 1050,
        price: 1690,
        tags: ['запечённый'],
        accent: '#0f766e',
    },
    {
        id: 'set-5',
        category: 'set',
        number: 5,
        title: 'Сет «Сакура»',
        description: 'Нежные роллы с креветкой, манго и соусом унаги.',
        pieces: 26,
        weight: 900,
        price: 1390,
        tags: ['сладкий'],
        accent: '#e11d48',
    },
    {
        id: 'set-6',
        category: 'set',
        number: 6,
        title: 'Сет «Токио»',
        description: 'Большой микс: спайси тунец, угорь, тобико и васаби-майо.',
        pieces: 36,
        weight: 1180,
        price: 1890,
        tags: ['на компанию'],
        accent: '#1a2024',
    },
]

export const MENU_SUSHI: MenuProduct[] = [
    {
        id: 'sushi-1',
        category: 'sushi',
        title: 'Нигири с лососем',
        description: 'Классическое нигири с свежим лососем и рисом.',
        price: 290,
        pieces: 2,
        weight: 80,
        tags: ['лосось'],
    },
    {
        id: 'sushi-2',
        category: 'sushi',
        title: 'Нигири с тунцом',
        description: 'Нежное нигири с тунцом средней прожарки.',
        price: 320,
        pieces: 2,
        weight: 80,
        tags: ['тунец'],
    },
    {
        id: 'sushi-3',
        category: 'sushi',
        title: 'Нигири с угрём',
        description: 'Угорь под соусом унаги и кунжутом.',
        price: 350,
        pieces: 2,
        weight: 85,
        tags: ['угорь'],
    },
    {
        id: 'sushi-4',
        category: 'sushi',
        title: 'Гункан с креветкой',
        description: 'Рис в водорослях нори с креветкой и соусом.',
        price: 310,
        pieces: 2,
        weight: 75,
        tags: ['креветка'],
    },
    {
        id: 'sushi-5',
        category: 'sushi',
        title: 'Сашими лосось',
        description: 'Ломтики свежего лосося без риса.',
        price: 490,
        pieces: 5,
        weight: 100,
        tags: ['лосось', 'хит'],
    },
    {
        id: 'sushi-6',
        category: 'sushi',
        title: 'Томаго',
        description: 'Сладкий японский омлет на рисовой подушке.',
        price: 240,
        pieces: 2,
        weight: 70,
        tags: ['вегетарианское'],
    },
]

export const MENU_ROLLS: MenuProduct[] = [
    {
        id: 'roll-1',
        category: 'roll',
        title: 'Филадельфия',
        description: 'Лосось, сливочный сыр, огурец, нори.',
        price: 420,
        pieces: 8,
        weight: 260,
        tags: ['хит', 'лосось'],
    },
    {
        id: 'roll-2',
        category: 'roll',
        title: 'Калифорния',
        description: 'краб, авокадо, огурец, икра тобико.',
        price: 380,
        pieces: 8,
        weight: 240,
        tags: ['лёгкий'],
    },
    {
        id: 'roll-3',
        category: 'roll',
        title: 'Дракон',
        description: 'Угорь, авокадо, огурец, соус унаги.',
        price: 490,
        pieces: 8,
        weight: 270,
        tags: ['угорь'],
    },
    {
        id: 'roll-4',
        category: 'roll',
        title: 'Спайси тунец',
        description: 'Тунец, острый соус, зелёный лук.',
        price: 450,
        pieces: 8,
        weight: 250,
        tags: ['острое'],
    },
    {
        id: 'roll-5',
        category: 'roll',
        title: 'Запечённый с лососем',
        description: 'Запечённый лосось, сыр, соус спайси.',
        price: 410,
        pieces: 8,
        weight: 255,
        tags: ['запечённый'],
    },
    {
        id: 'roll-6',
        category: 'roll',
        title: 'Маки с огурцом',
        description: 'Классические маки с свежим огурцом.',
        price: 220,
        pieces: 6,
        weight: 140,
        tags: ['вегетарианское'],
    },
]

export const MENU_DRINKS: MenuProduct[] = [
    {
        id: 'drink-1',
        category: 'drink',
        title: 'Coca-Cola',
        description: 'Классическая газировка.',
        price: 120,
        volume: 500,
        tags: ['газировка'],
    },
    {
        id: 'drink-2',
        category: 'drink',
        title: 'Sprite',
        description: 'Лимонная газировка.',
        price: 120,
        volume: 500,
        tags: ['газировка'],
    },
    {
        id: 'drink-3',
        category: 'drink',
        title: 'Зелёный чай',
        description: 'Охлаждённый зелёный чай без сахара.',
        price: 90,
        volume: 400,
        tags: ['чай'],
    },
    {
        id: 'drink-4',
        category: 'drink',
        title: 'Манго лassi',
        description: 'Йогуртовый напиток с манго.',
        price: 180,
        volume: 350,
        tags: ['хит'],
    },
    {
        id: 'drink-5',
        category: 'drink',
        title: 'Вода негазированная',
        description: 'Питьевая вода.',
        price: 80,
        volume: 500,
        tags: [],
    },
    {
        id: 'drink-6',
        category: 'drink',
        title: 'Апельсиновый сок',
        description: '100% сок без добавления сахара.',
        price: 150,
        volume: 330,
        tags: ['сок'],
    },
]

export function getMenuSetById(id: string): MenuSet | undefined {
    return MENU_SETS.find((item) => item.id === id)
}

export function getMenuProductById(id: string): MenuProduct | undefined {
    return [...MENU_SUSHI, ...MENU_ROLLS, ...MENU_DRINKS].find((item) => item.id === id)
}
